version: '3'

services:
  # Database
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      DB_HOSTNAME: localhost
      DB_USER: root
      MYSQL_ROOT_PASSWORD: root
      DB_DATABASE: TypeScriptExpress