version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    restart: always
    environment:
      database__client: mysql
      database__connection__host: db,
      database__connection__user: root,
      database__connection__password: password,
      database__connection__database: ghost,
    depends_on:
      - "db"
    networks:
      - my-network
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    ports:
      - "33063:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dados-banco:/var/lib/mysql
    networks:
      - my-network
volumes:
  dados-banco:
networks:
  my-network:
